const actionTypes = {
  SEARCH_REPOS:         'SEARCH_REPOS',
  SEARCH_REPOS_SUCCESS: 'SEARCH_REPOS_SUCCESS',
  SEARCH_REPOS_FAILURE: 'SEARCH_REPOS_FAILURE',
  WATCH_REPO:         'WATCH',
  WATCH_REPO_SUCCESS: 'WATCH_SUCCESS',
  WATCH_REPO_FAILURE: 'WATCH_FAILURE',
  UNWATCH_REPO:         'UNWATCH',
  UNWATCH_REPO_SUCCESS: 'UNWATCH_SUCCESS',
  UNWATCH_REPO_FAILURE: 'UNWATCH_FAILURE',
  FETCH_WATCHING_REPOS:         'FETCH_WATCHING_REPOS',
  FETCH_WATCHING_REPOS_SUCCESS: 'FETCH_WATCHING_REPOS_SUCCESS',
  FETCH_WATCHING_REPOS_FAILURE: 'FETCH_WATCHING_REPOS_FAILURE',
}

export default actionTypes
