const actionTypes = {
  SEARCH_REPOS:         'SEARCH_REPOS',
  SEARCH_REPOS_SUCCESS: 'SEARCH_REPOS_SUCCESS',
  SEARCH_REPOS_FAILURE: 'SEARCH_REPOS_FAILURE',
  WATCH:         'WATCH',
  WATCH_SUCCESS: 'WATCH_SUCCESS',
  WATCH_FAILURE: 'WATCH_FAILURE',
  UNWATCH:         'UNWATCH',
  UNWATCH_SUCCESS: 'UNWATCH_SUCCESS',
  UNWATCH_FAILURE: 'UNWATCH_FAILURE',
  FETCH_WATCHING_REPOS:         'FETCH_WATCHING_REPOS',
  FETCH_WATCHING_REPOS_SUCCESS: 'FETCH_WATCHING_REPOS_SUCCESS',
  FETCH_WATCHING_REPOS_FAILURE: 'FETCH_WATCHING_REPOS_FAILURE',
}

export default actionTypes
